name: desk_top_teacher
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.1

# Add regular dependencies here.
dependencies:
  firedart: ^0.9.7
  qr_flutter: ^4.1.0
#  fvp: ^0.12.0
  device_info_plus: ^9.1.1
  # pretty_qr_code: ^3.0.0
  media_kit: ^1.1.10+1                             # Primary package.
  media_kit_video: ^1.2.4                        # For video rendering.
  media_kit_libs_video: ^1.0.4
  url_launcher: ^6.2.2
  get: ^4.6.6

  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.9
